package com.article.entity;

import com.fasterxml.jackson.annotation.*;
import io.swagger.annotations.*;
import java.time.*;
import lombok.*;
import javax.persistence.*;

@JsonPropertyOrder({
    "slug_id",
    "slug",
    "title",
    "description",
    "body",
    "createdAt",
    "updatedAt"
})

@Data
@Entity
public class Article {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@JsonIgnore
	@ApiModelProperty(value = "autogenerated id")
	private Long id;

	@JsonProperty(value="id")
	@ApiModelProperty(value = "autogenerated UUid")
	private String slug_id;

	private String slug;

	private String title;

	private String description;

	private String body;

	@ApiModelProperty(value = "Date of creation of resources")
	private ZonedDateTime createdAt;

	@ApiModelProperty(value = "Date of updation of resources")
	private ZonedDateTime updatedAt;
}
